  map-name: "默认"
  server-ip: "play.example.com"
  lobby:
    world: world
    x: 0.0
    y: 64.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
  spawn-points:
      1:
          world: world
          x: 100.5
          y: 64.0
          z: -200.5
          yaw: 90.0
          pitch: 0.0
      2:
          world: world
          x: 150.5
          y: 70.0
          z: -180.5
          yaw: 0.0
          pitch: 10.0